Listagem de posts
zjefersound/agorium pull request #57
Opened 2024-09-04 17:46 UTC by zjefersound

# Listagem de posts

## Issue: #56 

## Change log:
- usePaginatedResource
- Atualização no serializer do Post no back end

## Checklist:

Antes de enviar seu código pra revisão verifique os requisitos abaixo:

- [ ] O código está escrito em inglês
- [ ] Sem warnings ou erros (console, ou logs do back end)
- [ ] Estilizações estão responsivas para smartphones e desktop (se aplicável)
- [ ] Swagger atualizado (se aplicável)

2024-09-04 17:50 UTC, joaozenaro commented on backend/src/Domain/Post.php
> +            'category' =>  [
É possível utilizar o jsonSerialize da categoria invés de acessar a propriedade manualmente?

2024-09-04 17:52 UTC, joaozenaro commented on backend/src/Domain/Post.php
> +            'tags' => array_map(fn($tag) => [
Se possível, a tag também poderia chamar o jsonSerialize. Algo como

```php
'tags' => array_map(fn($tag) => $tag->jsonSerialize(), $this->getTags()->toArray()),
```

2024-09-04 17:52 UTC, joaozenaro commented on backend/src/Domain/Post.php
> +            'user' => [
Se possível, utilize o jsonSerialize do usuario ao invés de mapear as propriedades manualmente

2024-09-04 18:14 UTC, joaozenaro requested changes

2024-09-04 18:14 UTC, joaozenaro commented on backend/src/Domain/Post.php
> +            'user' => [
Se possível, utilize o jsonSerialize do usuario ao invés de mapear as propriedades manualmente

2024-09-04 18:14 UTC, joaozenaro commented on backend/src/Domain/Post.php
> +            'category' =>  [
Se possível, utilize o jsonSerialize do usuario ao invés de mapear as propriedades manualmente

2024-09-04 18:14 UTC, joaozenaro commented on backend/src/Domain/Post.php
> +            'tags' => array_map(fn($tag) => [
Se possível, a tag também poderia chamar o jsonSerialize. Algo como

```php
'tags' => array_map(fn($tag) => $tag->jsonSerialize(), $this->getTags()->toArray()),
```

2024-09-04 20:18 UTC, gabrielmarafon approved these changes
Aprovado!

2024-09-05 03:04 UTC, joaozenaro approved these changes
<img src="https://media1.giphy.com/media/26tOZ42Mg6pbTUPHW/giphy.gif"/>

2024-09-05 04:07 UTC, merged