Layout página de ranking
zjefersound/agorium pull request #81
Opened 2024-09-14 19:06 UTC by gabrielmarafon

# Layout página de ranking

## Issue: #46 

## Change log:
-  Página Rankings

## Checklist:

Antes de enviar seu código pra revisão verifique os requisitos abaixo:

- [ ] O código está escrito em inglês
- [ ] Sem warnings ou erros (console, ou logs do back end)
- [ ] Estilizações estão responsivas para smartphones e desktop (se aplicável)
- [ ] Swagger atualizado (se aplicável)

2024-09-18 13:06 UTC, joaozenaro requested changes

2024-09-18 13:06 UTC, joaozenaro commented on frontend/src/pages/Rankings.tsx
> +                    @janete12312
Esses dados poderiam ser mockados?

2024-09-18 13:06 UTC, joaozenaro commented on frontend/src/pages/Rankings.tsx
> +export function Rankings() {
O componente está bem longo, é possível componentizar um pouco mais?

2024-09-18 20:40 UTC, zjefersound commented on frontend/src/pages/Rankings.tsx
> +        <NavigationCard />
Puxar a branch main na sua e usar <GlobalSidebar />

2024-09-18 20:40 UTC, zjefersound commented on frontend/src/pages/Rankings.tsx
> +export function Rankings() {
Complementando... 
Pode ter um componente de leaderboad e outro pra tabela

2024-09-19 22:43 UTC, joaozenaro approved these changes
<img src="https://media4.giphy.com/media/lq3rZDjnSU8rqfqehM/giphy-downsized-medium.gif"/>

2024-09-19 23:34 UTC, zjefersound requested changes

2024-09-19 23:34 UTC, zjefersound commented on frontend/src/components/shared/Podium.tsx
> +              "https://cdn.awsli.com.br/600x1000/2515/2515067/produto/23384010353bd9f5651.jpg"
item[1].user.avatar

2024-09-19 23:34 UTC, zjefersound commented on frontend/src/components/shared/Podium.tsx
> +            name={"teste"}
item[1].user.name

2024-09-19 23:34 UTC, zjefersound commented on frontend/src/components/shared/Podium.tsx
> +            name={"teste"}
msm coisa

2024-09-19 23:34 UTC, zjefersound commented on frontend/src/components/shared/Podium.tsx
> +              "https://cdn.awsli.com.br/600x1000/2515/2515067/produto/23384010353bd9f5651.jpg"
msm coisa

2024-09-19 23:34 UTC, zjefersound commented on frontend/src/components/shared/Podium.tsx
> +            name={"teste"}
msm coisa

2024-09-19 23:34 UTC, zjefersound commented on frontend/src/components/shared/Podium.tsx
> +              "https://cdn.awsli.com.br/600x1000/2515/2515067/produto/23384010353bd9f5651.jpg"
msm coisa

2024-09-19 23:34 UTC, zjefersound commented on frontend/src/examples/mocks/mocks.ts
> +    fullName: "CHUPISCO AZEDO COM LEITE FERMENTADO",
KKKKKKKKKKKKKKKKKKKK remover

2024-09-19 23:52 UTC, zjefersound approved these changes
<img src="https://media1.giphy.com/media/GazPMD1iWfgcM/giphy.gif"/>

2024-09-19 23:52 UTC, merged